version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./entrypoint.sql:/docker-entrypoint-initdb.d/db.sql
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
  redis:
    image: redislabs/rejson:latest
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    env_file:
      - ./.env
    ports:
      - ${REDIS_PORT}:6379
volumes:
  postgres-data: